Add: Read-modify-write (RMW) module
pulp-platform/snitch pull request #164
Opened 2021-06-21 10:05 UTC by fischeti

Read-modify-write adapter for byte-wise read and write accesses which addresses #152 . For byte-wise read accesses, the adapter just returns the masked data. For byte-wise write accesses, the adapter stalls the original request while performing a full-width read access followed by a masked modify and full-width write

The input and of the module consist of the following signals (the output signals are mirrored)
```sv 
   // Request-side channel
   input logic  mem_req_i,
   output logic mem_gnt_o,
   input        addr_t mem_addr_i,
   input        data_t mem_wdata_i,
   input        strb_t mem_strb_i,
   input logic  mem_we_i,
   output logic mem_rvalid_o,
   output       data_t mem_rdata_o
```

The protocol currently takes the following assumptions:
1. A valid handshake occurs when `req` and `gnt` are high. 
2. The data is read/written one cycle after a valid handshake and the `rvalid` signal is high for both read/write requests
3. A `gnt` is raised at the earliest one cycle after the `req` is raised

Open questions:
- Are the protocol assumptions correct? 
- Naming and location etc.: the module currently has its own folder `ip/spm_interface`. Could probably be placed somewhere else and maybe named differently. The interface is currently only used for testing purposes
- Which license header to use?

2021-06-21 11:09 UTC, zarubaf requested changes
> The protocol currently takes the following assumptions:
> 
> 1. A valid handshake occurs when `req` and `gnt` are high.

I would probably also prefer if it would be named `valid` and `ready`. Imho that is much more understandable (see the  `stream_to_mem` module).

> 2. The data is read/written one cycle after a valid handshake and the `rvalid` signal is high for both read/write requests

The `rvalid` can come `1..N` cycles after the `reg & gnt` condition. But at least one cycle.

> 3. A `gnt` is raised at the earliest one cycle after the `req` is raised

No `gnt` can come combinatorial in the same cycle (like the `valid`/`ready`).

> 
> Open questions:
> 
> * Are the protocol assumptions correct?

almost

> * Naming and location etc.: the module currently has its own folder `ip/spm_interface`. Could probably be placed somewhere else and maybe named differently. The interface is currently only used for testing purposes

I think eventually that should go into `common_cells`, but having it as an IP is fine for now 👍 

> * Which license header to use?

You can copy the license from existing modules `Solderpad 0.51`.

2021-06-21 11:09 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +        // If partial memory access (read or write) is detected perform RMW_READ first
I do not think we need to support partial reads. No bus master can actually do such a thing and as the memory has no known side-effect on reads I do not know whether this actually makes sense. So you can assume that this will only be on writes.

2021-06-21 11:09 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +    if (mem_rvalid_i && !(&mem_strb_i)) begin
Or, even better, as you are re-using that signal all over the place you probably want to introduce a signal called `partial_write`

```verilog
assign partial_write = mem_rvalid_i & mem_we_i & ~(&mem_strb_i)
```
Imho, it's better to be explicit about the signal and do not rely too much on common sub-expression elimination in the synthesizer.

2021-06-21 11:10 UTC, zarubaf commented
What I actually wanted to say is that you can simplify the FSM a bit when not considering partial reads (as indicated by the code comment) - I am expecting that this should very much simplify the FSM. If you want to keep the two FSMs separately that is okay by me but you could also make it one - however you like 😄

2021-06-21 15:55 UTC, fischeti commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +        // If partial memory access (read or write) is detected perform RMW_READ first
I removed support for pariatial reads. The FSM definitely looks much simpler now

2021-06-21 16:00 UTC, zarubaf requested changes

2021-06-21 16:00 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +      NORMAL: begin
I think there is one edge case that isn't yet handled. Theoretically, the protocol allows for an infinite amount of outstanding transactions we probably need to keep a counter to whether there are any outstanding otherwise we are potentially suppressing the answer of any outstanding transaction returning a datum.

So a counter that increments whenever a new transaction is accepted and decrements whenever it finishes should be sufficient. If it is `0` we can go into the next RMW state. We also need to make sure that we do not accept any in case the counter would overflow.

2021-06-21 16:00 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +        if (partial_write) begin
Like this, right? Otherwise, we would switch state even though the memory didn't accept yet.
```suggestion
        if (partial_write && mem_ready_i) begin
```

2021-06-22 07:30 UTC, fischeti commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +        if (partial_write) begin
Yes, you are right of course.

2021-06-22 10:24 UTC, fischeti commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +      NORMAL: begin
Makes sense. I have added `cnt_q` that prevents new transactions if is equal a configurable`MaxTxns` and stalls RMW requests if not equal `0`.

2021-06-22 12:24 UTC, zarubaf reviewed
Almost good to go, let's unify the two FSM - that makes it less code and easier to reason imho.

2021-06-22 12:24 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +  end
At this stage, I think the code would be more readable if the two FSMs would be merged.

2021-06-22 12:42 UTC, fischeti commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +     if (mem_rvalid_i) begin
The RMW operation starts only if the counter is `0` and should only have one outstanding transaction at any moment. But I will change it, it is probably a bit safer that way.

2021-06-22 12:50 UTC, fischeti commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +  end
Yes, I agree I will merge it.

2021-06-22 13:39 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +#(
Nitpicking, but a small comment what the module does would be quite good. That helps people understand the intent i.e., `/// This module breaks up sub-word accesses into read-modify-write accesses to support things like block ECC.`

2021-06-22 13:39 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +   output       mem_strb_t mem_strb_o,
I think to avoid confusion we can remove this port entirely.

2021-06-22 13:39 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +  assign rmw_ready = (cnt_q == '0);
```suggestion
  // Wait until we do not have any outstanding transactions anymore
  // since we are blocking the response channel with our `rmw` operation.
  assign rmw_ready = (cnt_q == '0);
```

2021-06-22 13:39 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +        mem_wdata_o = masked_wdata_q;
I think we have a protocol violation here, don't we? By keeping `mem_valid_o` asserted you are triggering potentially many more outstanding write transactions. Unfortunately, I do not see how we could do that without introducing another state. We would transition to `RMW_FINALIZE` when we get a `mem_ready_i`. And then from finalize to `NORMAL` on `mem_rvalid_i`. Does that make sense?

2021-06-22 13:39 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +        end
Potentially saves a cycle but introduces quite a long path between memory read and write. I would remove that (also makes it a bit simpler to reason about). I don't think that sub-word accesses on this memory are really a performance bottleneck. Do you agree?

2021-06-22 13:39 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +  `FFL(masked_wdata_q, masked_wdata_d, mem_rvalid_i, '0)
Hypothetically speaking we could condition the load condition also on the state (would help the synthesiser with inferring a clock gate).

2021-06-22 15:45 UTC, fischeti commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +        end
Yes, I haven't thought about the long path. Also, I think the FSM would look more comprehensible by removing it. I was not sure how much sacrificing a cycle impacts performance, but if this negligible than I totally agree on changing this.

2021-06-22 16:05 UTC, fischeti commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +        mem_wdata_o = masked_wdata_q;
Yes that is actually true. I will add an additional state `RMW_FINALIZE` in that case.

2021-06-23 09:48 UTC, zarubaf reviewed
Okay, sorry for yet another review - There is one minor modification that I thought would be nice: Removign the `mask_q` register by delaying the partial write transaction until we can directly save the masked data. Potentially saves quite some flip-flops. The rest is nits. I've annotated the change with change requests but of course, I am not sure if it is entirely correct.

2021-06-23 09:48 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +    mem_ready_o = mem_ready_i && txns_ready && rmw_ready;
We are unnecessarily stalling if the operation isn't `rmw`, right? That would be a fix:
```suggestion
    mem_ready_o = mem_ready_i & txns_ready & !partial_write;
```

2021-06-23 09:48 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +    mem_valid_o = mem_valid_i && txns_ready;
Nit (afaik from the style guide):
```suggestion
    mem_valid_o = mem_valid_i & txns_ready;
```

2021-06-23 09:48 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +        mem_rdata_o = '0;
Not necessary, right? We are just here when we do a read, so the `rdata` field will not carry any meaningful payload (saves some gates).
```suggestion
```

2021-06-23 09:48 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +        mem_rvalid_o = 1'b0;
```suggestion
        mem_rvalid_o = mem_rvalid_i;
```

2021-06-23 09:48 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +          mem_rvalid_o = 1'b1;
```suggestion
```

2021-06-23 09:48 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +  `FFL(mask_q, mask_d, partial_write, '0)
We could save the `mask_q` register here if we stall the incoming transaction until `masked_wdata_en`, right? Then we would still have `mask` available and generate the `masked_wdata_q` content.
```suggestion
```

2021-06-23 09:48 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +        mem_ready_o = 1'b0;
```suggestion
        mem_ready_o = mem_rvalid_i;
```

2021-06-23 09:48 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +  assign masked_wdata_en = mem_rvalid_i && (req_state_q == RMW_READ);
```suggestion
```

2021-06-23 09:48 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +      mask_d[i] = mem_strb_i[i/8];
```suggestion
      mask[i] = mem_strb_i[i/8];
```

2021-06-23 09:48 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +  assign masked_wdata_d = (mem_wdata_i & mask_q) | (mem_rdata_i & ~mask_q);
```suggestion
  assign masked_wdata_d = (mem_wdata_i & mask) | (mem_rdata_i & ~mask);
```

2021-06-23 09:48 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +  mem_data_t mask_q, mask_d;
```suggestion
  mem_data_t mask;
```

2021-06-23 13:40 UTC, fischeti commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +    mem_ready_o = mem_ready_i && txns_ready && rmw_ready;
This fix causes the `mem_ready_o` to never be asserted for rmw requests, so I have slightly modified it:
```suggestion
    mem_ready_o = mem_ready_i & txns_ready & !(partial_write & !rmw_ready);
```

2021-06-23 13:55 UTC, fischeti commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +    mem_valid_o = mem_valid_i && txns_ready;
Okay, I more or less follow [this styleguide](https://github.com/lowRISC/style-guides/blob/998f5a1f9146825b35bab87f944acca2424f90f3/VerilogCodingStyle.md#logical-vs-bitwise) which suggests logical `&&` operators for logic operations. But I have noticed that the existing codebase mostly follows the bitwise convention, so I will bring my code in line😄

2021-06-23 14:05 UTC, fischeti commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +  `FFL(mask_q, mask_d, partial_write, '0)
Yes, this should be possible. I am actually not sure why I initially instanstiated registers for the `mask`. But under the assumption that the `mem_strb_i` remains stable when stalling the incoming transaction, we can remove it.

2021-06-23 14:13 UTC, fischeti commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +  assign masked_wdata_en = mem_rvalid_i && (req_state_q == RMW_READ);
I don't quite understand this. We still need a enable signal for `masked_wdata_q`, right?

2021-06-28 08:36 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +    mem_ready_o = mem_ready_i & txns_ready & !(partial_write & !rmw_ready);
Somehow I have trouble reasoning over this. Shouldn't that be? I might also be wrong about this.
```suggestion
    mem_ready_o = mem_ready_i & txns_ready & !partial_write;
```

2021-06-28 08:53 UTC, fischeti commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +    mem_ready_o = mem_ready_i & txns_ready & !(partial_write & !rmw_ready);
https://github.com/pulp-platform/snitch/pull/164#discussion_r657112369
`partial_write` is asserted for RMW writes until a handshake occurs. But a handshake will not happen because `mem_ready_o` is never asserted due to `!partial_write`. Does that make sense, or did I miss anything?

2021-06-28 10:14 UTC, zarubaf commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +    mem_ready_o = mem_ready_i & txns_ready & !(partial_write & !rmw_ready);
Right, but you are overwriting `mem_ready_o` in `RMW_READ`, right - so that shouldn't be a problem? You do not want to handshake before that for RMW operations or otherwise we are loosing the byte-mask, aren't we?

2021-06-28 14:50 UTC, fischeti commented on hw/ip/spm_interface/src/spm_rmw_adapter.sv
> +    mem_ready_o = mem_ready_i & txns_ready & !(partial_write & !rmw_ready);
Yes you are actually correct. I think the issue I explained occured when `mem_ready_o` was not yet overwritten in `RMW_READ`. But in that case it is not needed anymore.

2021-06-28 14:54 UTC, fischeti commented
I have actually discovered another protocol violation. `mem_ready_o` should not be asserted in the `RMW_READ` state but it should be delayed until the `mem_ready_i` is asserted in the `RMW_MODIFY_WRITE` state. Otherwise we lose the address.

2021-06-29 08:39 UTC, zarubaf approved these changes
Good catch, LGTM to me now!

2021-06-29 08:39 UTC, merged