periph: Performance counters
pulp-platform/snitch pull request #255
Opened 2021-09-15 19:49 UTC by fischeti

This PR integrates the existing performance counters into the runtime. The DMA performance metrics can now also be tracked (#247). Further, it fixes an issue where the `hwext` registers were not generated correctly by the `regtool`. It also adds the capability to reset counters at runtime.

2021-09-16 13:01 UTC, zarubaf requested changes
Looks good to me. Only thing is that we probably don't want to have the other counters in there as well, right? Maybe making it parameterizable or so.

2021-09-16 13:01 UTC, zarubaf commented on hw/ip/snitch_dma/src/axi_dma_perf_counters.sv
>            dma_perf_d.aw_valid_cnt = dma_perf_q.aw_valid_cnt + 'h1;
I don't think we want this, right? That gives a register for each perf counter (so will get quite big).

2021-09-16 13:09 UTC, fischeti commented on hw/ip/snitch_dma/src/axi_dma_perf_counters.sv
>            dma_perf_d.aw_valid_cnt = dma_perf_q.aw_valid_cnt + 'h1;
You mean the `dma_perf_q`? Those are the old performance counters and are not connected to anywhere, so I assume they will not be synthesized. But I can also delete or parametrize them

2021-09-16 15:46 UTC, zarubaf commented on hw/ip/snitch_dma/src/axi_dma_perf_counters.sv
>            dma_perf_d.aw_valid_cnt = dma_perf_q.aw_valid_cnt + 'h1;
True, yes maybe a parameter would make the indent a but clearer. Then we are good to go!

2021-09-20 11:02 UTC, zarubaf approved these changes
Awesome @fischeti, super nice infrastructure! LGTM you can merge whenever you are ready :-)

2021-09-20 11:08 UTC, merged