Feature/fpnew simd dotp
pulp-platform/snitch pull request #256
Opened 2021-09-16 07:34 UTC by GiannaP

Changes are all related to FPnew.

# Changes
## General
- update opcodes to support new instructions `vsumex`, `dotpex`
- update opcodes (for RTL) to `opcodes-flt-occamy` which uses new CSR based encoding

## RTL
- add FP8alt support (configuration parameter 'xfp8alt')
- add Mulex and Macex support depending on the FMA architecture configuration (needs `MERGED`)
- new CSR based encoding for the alternate floating point formats `fp8alt` and `fp16alt`
  - `fcsr` adds two bits: `src_fmt` and `dst_fmt`, if set to 1 alternate format is selected for fp instructions
- add FP8alt support (configuration parameter 'xfdotp')
- add `DOTP` instructions to decoder and update FPnew to version with new OpGroup `DOTP`

## Banshee
- comment out fp instructions not supported by opcodes and HW based on new opcodes (some instruction definitions changed)
- rename some instructions based on opcode instruction renaming for consistency

2021-09-16 07:56 UTC, SamuelRiedel approved these changes
The Banshee part looks good to me. Will we need/enable those instructions again in the future?

2021-09-16 09:12 UTC, stmach requested changes
Looks very good, please quickly comment on / look at the points I raised.

2021-09-20 07:56 UTC, zarubaf approved these changes
Nice work guys!

2021-09-20 12:48 UTC, GiannaP commented on hw/ip/snitch/src/snitch.sv
> +              if (!exception) fcsr_d.fmode = fpnew_pkg::fmt_mode_t'(opa[1:0]);
fixed in commit: a6ce709819848a2c1ba72c1a7cf4c478fce84236

2021-09-20 12:51 UTC, GiannaP commented on hw/ip/snitch_cluster/src/snitch_fp_ss.sv
> +          dst_fmt    = fpnew_pkg::FP16ALT;
fixed in commit: 58f02143b93414064c2b0f1823b1efd7fb7e7b5e

Note: `src_fmt` is ignored for signle-format fp operations. This allows to write the encoding csr for non-alternate/alternate format only once when combining expanding instructions (which need a correct `src_fmt`) and single-format instructions. (which use `dst_fmt` for the actual src and dst fmt given to FPnew)

2021-09-20 13:00 UTC, GiannaP commented
> The Banshee part looks good to me. Will we need/enable those instructions again in the future?

`vsum.{b,h,s}` is coming again in the next 1-2 days, `dotp.{b,h,s}` is currently not planned but might come in future, not sure. So we could think about completely removing the latter.

2021-09-23 12:06 UTC, merged