Extend docs
pulp-platform/snitch pull request #444
Opened 2022-10-28 12:47 UTC by colluca

2022-10-28 16:51 UTC, colluca commented
@paulsc96 There is one last thing I don't understand about the FREP instructions, and it's the `stream_ctl` field which is not reported in the original paper. Do you know what its purpose is? I could add it to the documentation and then it should be complete.

2022-11-03 16:59 UTC, paulsc96 requested changes
I think that if we add a dedicated publication section, we should also update the main README accordingly (see bottom).

2022-11-03 16:59 UTC, paulsc96 commented on mkdocs.yml
> +repo_url: https://github.com/colluca/snitch
Let's revert this to its original state

2022-11-03 23:12 UTC, colluca commented on mkdocs.yml
> +repo_url: https://github.com/colluca/snitch
Good catch, thanks!

2022-11-03 23:50 UTC, colluca commented
> I think that if we add a dedicated publication section, we should also update the main README accordingly (see bottom).

This is my proposal, what do you think? I think it is important to emphasize that anyone using the core should cite the Snitch paper, whereas the other works are more specific. I would maybe move the SSR paper also below the separator line.

2023-01-11 11:40 UTC, paulsc96 approved these changes

2023-01-11 11:41 UTC, merged