Update/cva6 ci fix
pulp-platform/snitch pull request #480
Opened 2023-03-30 09:42 UTC by CyrilKoe

Replaces https://github.com/pulp-platform/snitch/pull/460

Same updates after rebasing on the latest master and adding gitlab modelsim tests.

Changes

    hw/system/occamy
        fpga : new scripts, new IPs, possiblility to add an external JTAG on GPIOs, new constraints,
            bottrom : removed compilations products, bottrom.S now enables snitch to wake up and jump to a function pointer, changed makefile to rely on $UBOOT_SPL_BIN instead of full CVA6 SDK, changed DTS for new IPs and recent interrupt changes in HW, added PCIe "bootmode".
            openocd_scripts : added scripts for VCUs and GPIO JTAG
    .github : added the pulp action flow
    .gitlabci : added a FPGA compilation CI (no boot yet), it relies on a branch of the HERO repository for now which is not great.

2023-03-30 16:28 UTC, GiannaP requested changes
I have a few smaller nitpicks and questions, otherwise LGTM!

2023-03-31 10:01 UTC, CyrilKoe commented on .gitlab-ci.yml
> +    if ! $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh --ignore-uncommitted-changes lookup occamy_vcu128; then
Yes because the script regenerates the hw with 1 cluster before

2023-03-31 10:01 UTC, CyrilKoe commented on util/bin2jtag.py
> +import bin2coe.convert
it was added in previous commits already

2023-03-31 10:01 UTC, CyrilKoe commented on hw/vendor/pulp_platform_tech_cells_generic/src/fpga/tc_clk_xilinx.sv
> +// Copyright 2019 ETH Zurich and University of Bologna.
No it's a leftover indeed

2023-03-31 15:24 UTC, GiannaP commented on util/bin2jtag.py
> +import bin2coe.convert
perfect :)

2023-03-31 15:26 UTC, GiannaP commented on hw/vendor/pulp_platform_tech_cells_generic/src/fpga/tc_clk_xilinx.sv
> +// Copyright 2019 ETH Zurich and University of Bologna.
ok, then let's merge once this is removed!

2023-04-03 06:14 UTC, CyrilKoe commented
I think it's good

2023-04-03 06:16 UTC, CyrilKoe commented
GitlabCI timedout because the fpga build is manual (takes 8h), I started it on github mirrors and then we just need to restart the ci check here.

2023-04-04 07:12 UTC, CyrilKoe commented
Is there any merge conflicts ?

2023-04-04 07:37 UTC, GiannaP approved these changes

2023-04-04 07:38 UTC, merged